### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m2-evaluacion-intermedia-claradios#1]
Really cool job @claradios  !!!

Here you have some tips to improve the exercise:

### JavaScript

- [x] Use descriptive variables names instead of one-letter ones
- [x] If we store a value in a constant/variable, we should use the constant/variable instead of its value (main.js, lines 9 and 10).

### HTML

- [x] "Introduce aquí tu número" should be the label element content

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button, and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by claradios** [comment]
Hi @oneeyedman !

I have made all corrections and improvements you suggested. Also I tried to give my own touch to the game. 

NOTE: **I worked on a different branch called:  improve**.

Thanks for your support
